@startuml
skinparam classAttributeIconSize 0

package ch.giuliobosco.freqline.acc {
    class AccGenerator{
        + {static} void turnGeneratorOn(Connection connection, String keyC)
        + {static} void turnGeneratorOff(Connection connection, String keyC)
        + {static} void turnGeneratorOn(Connection connection, String, long timer)
        + {static} void updateDecibel(Connection connection, int userId, int decibel)
        - {static} void request(String url)
        - {static} String buildUrl(Connection connection, String address, String keyC, boolean on)
        - {static} String buildUrl(Connection connection, String address, String keyC, long timer)
        - {static} int getFrequence(Connection connection, String keyC)
    }
}

@enduml