@startuml

alt "do {} while(response!=ok)":
    arduino -> raspberry : "command(command, value)"
    raspberry --> arduino : "response"
end

alt "do {} while(response!=ok)":
    raspberry -> arduino : "command(command, value)"
    arduino --> raspberry : "response"
end

@enduml