@startuml

alt "do {} while(response!=ok)":
    arduino -> serial : "command(command, value)"
    serial --> arduino : "response"
end

alt "do {} while(response!=ok)":
    serial -> arduino : "command(command, value)"
    arduino --> serial : "response"
end

@enduml