@startuml acc communication between arduino and server

Arduino -> Server : http(keyC, action, content)
Server -> Database : isValid(keyC)

alt isValid(keyC) == true
    Database --> Server : key ok
    
    Server -> Database : getFrequence(keyC)
    Database --> Server : frequence

    alt action == conf
        Server -> Database : getConf(keyC)
        Database --> Server : conf
        Server --> Arduino : ok(conf)
    else action == mic
        Server -> Database : getGeneratorStatus(keyC)
        Database --> Server : status

        Server -> Database : setGeneratorStatus(keyC, !status)
        alt status == 1
            Server --> Arduino : ok(!status, frequence)
        else status == 0
            Server -> Database : getMicTimer(keyC)
            Database --> Server : micTimer
            Server --> Arduino : ok(!status, frequence, micTimer)
        end
    else action == remote
        alt content == toggle
            Server -> Database : getGeneratorStatus(keyC)
            Database --> Server : status
            Server -> Database : setGeneratorStatus(keyC, !status)
            Server --> Arduino : ok(!status, frequence)
        else content == 1
            Server -> Database : setGeneratorStatus(keyC, 1)
            Server --> Arduino : ok(1, frequence)
        else content == 0
            Server -> Database : setGeneratorStatus(keyC, 0)
            Server --> Arduino : ok(0, frequence)
        end
    end
else else
    Database --> Server : wrong key
    Server --> Arduino : error
end

@enduml
