@startuml communication web set mic timer

actor User
entity Server
database Database

User -> Server : setMicTimer(timer)
Server -> Database : getPermissionsFor(user)
Database --> Server : permissionsFor

alt permissionsFor.contains(user)
    Server -> Database : setMicTimer(timer)
    Server --> User : ok 
else 
    Server --> User : error
end

@enduml