@startuml

participant "Server Thread" as server
participant "Serial Thread" as serial
participant "Mic Thread" as micT
participant "Arduino" as arduino
database "Database" as db

server -> serial : addCommand(command, value)
server -> db : update db

alt while (true)
    serial -> serial : loadCommand()
    db --> serial : loadDataFromDB()
    serial -> arduino : command(command, value)
    arduino --> serial : response(type, value)
    arduino -> serial : command(command, value)
    serial --> arduino : response(type, value)

    serial -> serial : runCommand()

    alt command == mic
        serial -> micT : start()
        micT -> micT : wiatSeconds
        micT -> serial : addCommand(command, value)
    end
end

@enduml