@startuml

:Admin User: as AdminUser

User <|-- AdminUser

(Admin user views) as AdminPage
(Configure generator) as NormalPage
(Edit DB) as edb
(Controller) as ctrl
(remote) as remote
(microphone) as mic
:Generator status: as status

AdminUser ---> AdminPage : manage users
AdminPage ---> edb : update db
edb ---> ctrl : load configuration

User ---> NormalPage : on/off generator\nchange frequence\nchange decibel\nchange timer
NormalPage ---> ctrl

User ---> mic : loud noise
mic ---> ctrl : turn generator on\nset timer

User ---> remote : on/off generator\nor toggle
remote ---> ctrl

ctrl ---> status : update generator\nstatus
ctrl ---> edb : update db

@enduml
